config/routes.rb
Blogger::Application.routes.draw do
  devise_for :users

  resources :authors

	root :to => 'articles#index'
  get "tags/index"

  get "tags/show"

	resources :comments
    resources :articles
    resources :tags
    resources :author_sessions

    match 'login' => 'author_sessions#new', :as => :login
    match 'logout' => 'author_sessions#destroy', :as => :logout

end

app/models/article.rb
class Article < ActiveRecord::Base
	attr_accessible :tag_list, :title, :body, :image
  has_many :comments
  has_many :taggings
  has_many :tags, :through => :taggings
  has_attached_file :image

  def tag_list
  	self.tags.collect do |tag|
  		tag.name
  	end.join(", ")
  end

  def tag_list=(tags_string)
  	self.taggings.destroy_all
  	
  	tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq

    tag_names.each do |tag_name|
      tag = Tag.find_or_create_by_name(tag_name)
      tagging = self.taggings.new
      tagging.tag_id = tag.id
    end
  end
end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :username, :email, :password, :password_confirmation

  validates_confirmation_of :password, :message => "should match confirmation", :if => :password
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :author_name, :body

  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  has_many :taggings
  has_many :articles, :through => :taggings

  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  attr_accessible :article_id, :tag_id
  belongs_to :article
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all
	end

	def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id 
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(params[:article])
		@article.save
		flash[:message] = "Article '#{@article.title}' Created!"
		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		flash[:message] = "Article '#{@article.title}' Destroyed!"
		redirect_to articles_path
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		@article.update_attributes(params[:article])

		flash[:message] = "Article '#{@article.title}' Updated!"

		redirect_to article_path(@article)
	end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end

    before_filter :zero_authors_or_authenticated, :only => [:new, :create]

    def zero_authors_or_authenticated
      unless Author.count == 0 || current_user
        redirect_to root_path
        return false
      end
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		article_id = params[:comment].delete(:article_id)

		@comment = Comment.new(params[:comment])
		@comment.article_id = article_id

		@comment.save

		redirect_to article_path(@comment.article)
end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  	@articles = Article.all 
  end

  def show
  	@tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def tag_links(tags)
		links = tags.collect{|tag| link_to tag.name, tag_path(tag)}
		return links.join(", ").html_safe
end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div class="comment">
	<p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later
	<h4>Comment by <%= comment.author_name %></h4>
	<p><%= comment.body %></p>
</div>

app/views/articles/_comment_form.html.erb
<h3>Post a Comment</h3>

<%= form_for @comment do |f| %>
<%= f.hidden_field :article_id %>
<p>
	<%= f.label "Your Name" %><br/>
	<%= f.text_field :author_name %>
</p>
<p>
	<%= f.label "Your Comment" %><br/>
	<%= f.text_area :body %>
	
	<%= f.submit 'Submit' %>
</p>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article, :html => {:multipart => true}) do |f| %>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :body %><br />
		<%= f.text_area :body %>
	</p>
	
		<p>
			<%= f.label :tag_list %><br />
			<%= f.text_field :tag_list %>
		</p>

<p>
	<% if @article.image_file_name %>
	<%= image_tag @article.image.url %><br/>
	<% end %>
	<%= f.label :image, "Attach an Image" %><br />
	<%= f.file_field :image %>
</p>


    <p>
		<%= f.submit %>
	</p>
	<% end %>

app/views/articles/edit.html.erb
<h1>Edit a Resource</h1>

<%= render :partial => 'form' %>

app/views/articles/index.html.haml
%ul
  -@articles.each do |article|
    %li= link_to article.title, article_path(article) 
    

app/views/articles/new.html.erb
<h1>Create a New Resource</h1>

<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>Tags: <%= tag_links(@article.tags) %></p>
<p><%= image_tag @article.image.url %></p>
<p><%= @article.body %></p>



<h3>Comments (<%= @article.comments.count %>)</h3>
<%= render :partial => 'comment', :collection => @article.comments %>

<%= render :partial => 'comment_form' %>
<%= link_to "<< Back to Resources", articles_path %>
<%= link_to "delete", article_path(@article), :method => :delete,  :confirm => "Really Delete Resource?" %>

<%= link_to "Edit Resource", edit_article_path(@article) %>
<% if logged_in? %>
	<% end %>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <!-- <th>Crypted password</th> -->
    <!-- <th>Salt</th> -->
    
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.username %></td>
    <td><%= author.email %></td>
    <!-- <td><%= author.crypted_password %></td> -->
    <!-- <td><%= author.salt %></td> -->
    <td><%= link_to 'Show', author %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @author.username %>
</p>

<p>
  <b>Email:</b>
  <%= @author.email %>
</p>

<p>
  <b>Crypted password:</b>
  <%= @author.crypted_password %>
</p>

<p>
  <b>Salt:</b>
  <%= @author.salt %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Ruby Resources"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Ruby Resources
          .container.nav-collapse
            %ul.nav
              %li= link_to "All Tips & Resources", articles_path
              %li= link_to "All Users #TODO", "/path2"
              %li= link_to "Add New Tip or Resource", new_article_path

    .container

      .content
        .row
          .span9
            = yield
          .span3
            .well.sidebar-nav
              -#%h3 Sidebar
              %ul.nav.nav-list
                %li.nav-header Welcome
                - if logged_in?
                  = "Logged in as #{current_user.username}"
                  = link_to "(logout)", logout_path
                - else
                  = link_to "(login)", login_path
                  Logged out

    
      %footer
        %p &copy; BayCoRuby 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/tags/index.html.erb
<h1>Tags#index</h1>
<p>Find me in app/views/tags/index.html.erb</p>

app/views/tags/show.html.erb
<h1>Article Tagged with <%= @tag.name %></h1>

<ul>
	<% @tag.articles.each do |article| %>
	<li><%= link_to article.title, article_path(article) %></li>
	<% end %>
</ul>